# Lathe plan: a single-file HTML/JS retro shooting game, generated by the model and gated TWO ways:
#   1) structural  — asserts on the file text (has a canvas, a game loop, key handlers, a score)
#   2) functional  — a Playwright script loads it in real Chromium and proves it animates + responds
# This is the ARTIFACTS path (whole-file generation), NOT the Python FUNCTIONS path. Proof the harness
# can build + verify browser code, not just Python. (exec fields must be string LITERALS — validator rule.)
OUT_DIR = "projects/agentic-harness"
MODULE_NAME = "shooter_game_plan"
HEADER = ""
GLUE = ""
FUNCTIONS = []

ARTIFACTS = [
    {
        "path": "_artifacts/shooter.html",
        "model": "claude",   # routes to the analyst endpoint (127.0.0.1:8787 -> fable), capable enough for a game
        "prompt": (
            "Create ONE self-contained HTML file: a simple retro top-down/vertical arcade SHOOTING game.\n"
            "Hard requirements:\n"
            "- Starts with <!DOCTYPE html>; everything (HTML, CSS, JS) inline in this single file; no external URLs.\n"
            "- Use a <canvas> element and render the game with its 2D context.\n"
            "- A continuous game loop driven by requestAnimationFrame.\n"
            "- Keyboard controls via keydown/keyup: ArrowLeft/ArrowRight (or A/D) move the player ship, Space shoots.\n"
            "- The player ship fires bullets; enemies spawn and move; a bullet hitting an enemy destroys it.\n"
            "- Track and display a numeric score (increment on enemy destroyed); show it as on-screen text.\n"
            "- Must run immediately on load (self-starting or start on first key/click); no build step, no assets.\n"
            "Output ONLY the file contents - no prose, no markdown fences."
        ),
        "tests": [
            "assert '<!doctype html' in content.lower()",
            "assert '<canvas' in content.lower()",
            "assert 'getcontext' in content.lower()",
            "assert 'requestanimationframe' in content.lower()",
            "assert ('keydown' in content.lower()) or ('keyup' in content.lower())",
            "assert ('arrowleft' in content.lower()) or (\"'a'\" in content.lower()) or ('keya' in content.lower())",
            "assert 'score' in content.lower()",
            "assert '<script' in content.lower()",
        ],
        "functional": (
            "import os\n"
            "from playwright.sync_api import sync_playwright\n"
            "path = os.environ['ARTIFACT_FILE']\n"
            "url = 'file:///' + path.replace('\\\\', '/')\n"
            "errors = []\n"
            "with sync_playwright() as p:\n"
            "    browser = p.chromium.launch()\n"
            "    page = browser.new_page()\n"
            "    page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)\n"
            "    page.on('pageerror', lambda e: errors.append(str(e)))\n"
            "    page.goto(url)\n"
            "    page.wait_for_timeout(400)\n"
            "    page.mouse.click(300, 300)\n"
            "    size = page.eval_on_selector('canvas', 'c => ({w: c.width, h: c.height})')\n"
            "    assert size['w'] > 0 and size['h'] > 0, 'canvas has zero size'\n"
            "    for k in ('Space', 'ArrowRight', 'ArrowLeft', 'Space'):\n"
            "        page.keyboard.press(k)\n"
            "        page.wait_for_timeout(120)\n"
            "    frame_a = page.eval_on_selector('canvas', 'c => c.toDataURL()')\n"
            "    page.wait_for_timeout(700)\n"
            "    frame_b = page.eval_on_selector('canvas', 'c => c.toDataURL()')\n"
            "    browser.close()\n"
            "assert not errors, 'JS errors on the page: ' + ' | '.join(errors[:3])\n"
            "assert frame_a != frame_b, 'canvas did not change over time - not a live/animating game'\n"
            "print('FUNCTIONAL PASS: canvas present, no JS errors, animates after input')\n"
        ),
        "fallback_after": 2,
    }
]
