"""hreview.py — the harness CE REVIEW GATE (PROCESS.md Stage 5.5). Runs a capped, READ-ONLY Compound-Engineering
review over specific files using the persona lens selected for the change domain, archives findings to docs/ce/.
CE never edits code (--permission-mode plan). Real findings are folded into the OWNING plan + regenerated by the
engine (never hand-edit generated code). Ported from the canonical a product harness 2026-06-29; project-generic.

Uses the VENDORED Compound-Engineering reviewer personas (ce_personas/, MIT — CE's actual code, refreshed from
github.com/EveryInc/compound-engineering-plugin; see ce_personas/NOTICE.md), NOT reimplementations. Lathe's own
field-derived doctrine is layered on as a separate PROJECT ADDENDUM per lens.

Usage:  python hreview.py <lens> <file1> [file2 ...]
        lens: security | correctness | adversarial | data | perf | reliability | api | maintainability | testing | ui
"""
import subprocess, sys, os, json, urllib.request

APP = os.environ.get("HARNESS_ACTIVITY_URL", "")   # optional activity feed; empty = no-op (generic project)
ROOT = os.path.dirname(os.path.abspath(__file__))   # the project this hreview lives in
_CE_DIR = os.environ.get("LATHE_CE_PERSONAS") or os.path.join(ROOT, "ce_personas")   # VENDORED CE persona defs (see NOTICE.md)

# Each lens maps to the VENDORED Compound-Engineering reviewer persona (its ACTUAL definition file — we use CE's
# code, not a reimplementation) + an optional Lathe PROJECT ADDENDUM (field-derived doctrine from our own bug
# reports, kept SEPARATE from CE's). Refresh the personas from upstream per ce_personas/NOTICE.md.
LENS = {
    "security":       ("security-reviewer.md", ""),
    "correctness":    ("correctness-reviewer.md",
                       "agreement/parity != ground truth — flag any check that only verifies two things MATCH "
                       "(two impls agree, output==baseline) without an INDEPENDENT oracle; a test that passes when both sides are wrong is not a test."),
    "adversarial":    ("adversarial-reviewer.md",
                       "sample the WORST and EMPTY cases, never the representative one — empty, all-same, all-ties, "
                       "single element, max scale, degenerate/collapsed distributions; show what each breaks."),
    "data":           ("data-integrity-guardian.md",
                       "derived data must carry + be checked against its inputs' version (staleness); two stores of 'the same' data must agree or one be declared derived; "
                       "no dangling FKs / orphan rows; code that is unit-correct but was NEVER run on the real corpus."),
    "perf":           ("performance-reviewer.md", ""),
    "reliability":    ("reliability-reviewer.md",
                       "hunt SILENT FAILURE — every try/except that swallows (pass/continue/return default-or-empty) and masks a real error or empty output; "
                       "is the worst-input empty result distinguishable from success?"),
    "api":            ("api-contract-reviewer.md", ""),
    "maintainability":("maintainability-reviewer.md", ""),
    "testing":        ("testing-reviewer.md", ""),          # CE's testing reviewer — a natural fit for Lathe's test-first model
    "ui":             ("julik-frontend-races-reviewer.md", ""),
}


def _load_persona(fname):
    """The REAL Compound-Engineering reviewer definition (vendored in ce_personas/, MIT — see NOTICE.md). We use
    CE's expertise verbatim and drop only its trailing '## Output format' section (CE emits a JSON schema for its
    own harness; Lathe supplies its own output format below)."""
    try:
        txt = open(os.path.join(_CE_DIR, fname), encoding="utf-8").read()
    except OSError:
        return ""
    i = txt.find("## Output format")
    return txt[:i].rstrip() if i > 0 else txt.rstrip()


def _log(title, detail, status):
    if not APP:
        return
    try:
        body = json.dumps({"kind": "review", "title": title, "detail": detail, "status": status}).encode()
        urllib.request.urlopen(urllib.request.Request(APP + "/api/admin/activity", data=body,
                               headers={"Content-Type": "application/json"}, method="POST"), timeout=5).read()
    except Exception as e:
        if "refused" not in str(e).lower():                # B7: the activity feed is optional — swallow connection-refused noise
            print("(activity log skipped: %s)" % e)


def main():
    if len(sys.argv) < 3:
        print("usage: python hreview.py <lens> <file1> [file2 ...]  | lens: " + ", ".join(LENS)); return 2
    lens, files = sys.argv[1], sys.argv[2:]
    if lens not in LENS:
        print("unknown lens '%s' | choose: %s" % (lens, ", ".join(LENS))); return 2
    persona_file, addendum = LENS[lens]
    persona = _load_persona(persona_file)                 # CE's REAL reviewer definition (vendored)
    # FIX: review files anywhere, not just under cwd. Pass ABSOLUTE paths and run claude from their
    # common-ancestor dir so its read sandbox covers all of them (else files above cwd are denied).
    abs_files = [os.path.abspath(f) for f in files]
    try:
        _root = os.path.commonpath(abs_files)
    except ValueError:                       # files span different drives -> no common path
        _root = ROOT
    if not os.path.isdir(_root):             # single file -> _root IS the file; also a typo'd/nonexistent arg
        _root = os.path.dirname(_root)
    if not os.path.isdir(_root):             # STILL not a real dir (e.g. a path that doesn't exist on disk) ->
        _root = ROOT                         # fall back to a guaranteed-valid cwd so CreateProcess can't WinError 267
    flist = "\n".join("  - " + f for f in abs_files)
    _orient = ""                                          # token-lean ctags repo-map so the reviewer sees the surrounding structure cheaply
    try:
        _td = os.path.join(ROOT, "tools")
        if _td not in sys.path:
            sys.path.insert(0, _td)
        from repomap import ctags_available, render_map
        from context_helpers import trim_for_context
        if ctags_available():
            _mp = render_map([_root]) or ""
            _mp = "\n".join(l for l in _mp.splitlines() if not l.split(":", 1)[0].strip().endswith(".json"))  # drop pins/data noise
            if _mp.strip():
                _orient = ("\n\n## PROJECT STRUCTURE (ctags orientation — the surrounding code, token-lean; "
                           "use it to catch duplication or wrong integration)\n" + trim_for_context(_mp, 1800))
    except Exception:
        _orient = ""                                       # ctags optional — reviewer still gets full file contents
    _hdr = persona if persona else ("You are a rigorous %s reviewer. Read the files adversarially and find real defects." % lens)
    _add = ("\n\n## PROJECT ADDENDUM (Lathe field-derived — ADDITIONAL to the above, from our own bug reports)\n" + addendum) if addendum else ""
    prompt = (_hdr + _add + _orient +
              "\n\n## YOUR TASK NOW\n"
              "Apply the expertise above to review these files (absolute paths). This is NOT a git repo — READ them directly:\n" + flist +
              "\n\nOUTPUT (this OVERRIDES any output-format instruction above): findings ONLY, each on its own block:\n"
              "SEVERITY (critical/high/medium/low) | file:symbol | the issue (+ a concrete failing input or exploit) | the fix.\n"
              "Rank by severity. If nothing material, say so plainly. Do NOT edit any file; do NOT call ExitPlanMode or any "
              "planning/approval tool — just read and output findings as your SINGLE FINAL message (that final message is the "
              "ONLY thing captured, so never say 'see above' and never write findings to a file).")
    os.makedirs(os.path.join(ROOT, "docs", "ce"), exist_ok=True)
    out = os.path.join(ROOT, "docs", "ce", "review_%s.txt" % lens)
    _log("CE review: " + lens, "%d file(s)" % len(files), "wip")
    # B3/D3: try analyst methods in an order set by explicit config; fall back to the next on ANY non-usable
    # response (connection failure, error, timeout, or empty/whitespace completion). Never hang.
    import tempfile, shutil
    _timeout = int(os.environ.get("CLAUDE_TIMEOUT", "180"))
    _force = os.environ.get("LATHE_REVIEW_USE_CLI")       # "1"=CLI-first, "0"=endpoint-only, unset=auto
    _url_set = bool(os.environ.get("HARNESS_CLAUDE_URL"))  # D3: a user-configured endpoint wins; CLI is the fallback
    _have_cli = bool(shutil.which("claude"))

    def _via_cli():
        _pf = tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8")
        _pf.write(prompt); _pf.close()
        try:                                              # Windows: `claude` is an npm .CMD shim -> shell=True, stdin
            r = subprocess.run('claude -p --model opus --permission-mode plan --max-budget-usd 6 < "%s"' % _pf.name,
                               shell=True, capture_output=True, text=True, cwd=_root, timeout=_timeout)
            return (r.stdout or "") + (r.stderr or "")
        except Exception as _e:
            sys.stderr.write("hreview: claude CLI unusable (%s) — trying next analyst\n" % _e)
            return ""
        finally:
            try: os.unlink(_pf.name)
            except Exception: pass

    def _via_endpoint():
        try:
            _td = os.path.join(ROOT, "tools")
            if _td not in sys.path:
                sys.path.insert(0, _td)
            from request_spec import request_spec
            _blobs = []                                   # endpoint models can't read files — embed contents inline
            for _f in abs_files:
                try:
                    _blobs.append("### FILE: %s\n```\n%s\n```" % (_f, open(_f, encoding="utf-8", errors="replace").read()))
                except Exception as _e:
                    _blobs.append("### FILE: %s (unreadable: %s)" % (_f, _e))
            _eprompt = prompt + "\n\n## FILE CONTENTS (review THESE directly — do not ask for access)\n" + "\n\n".join(_blobs)
            return request_spec(_eprompt) or ""
        except Exception as _e:
            sys.stderr.write("hreview: analyst endpoint unusable (%s) — trying next analyst\n" % _e)
            return ""

    if _force == "0":
        _order = [_via_endpoint]
    elif _force == "1":
        _order = [_via_cli, _via_endpoint]
    elif _url_set:                                        # D3: explicit URL preferred, CLI fallback
        _order = [_via_endpoint, _via_cli]
    else:
        _order = [_via_cli, _via_endpoint]

    txt = ""
    for _method in _order:
        if _method is _via_cli and not _have_cli:
            continue
        txt = _method()
        if txt.strip():                                   # usable -> done; else fall back to the next method
            break
    if not txt.strip():
        txt = "[review unavailable: no usable analyst — CLI and HARNESS_CLAUDE_URL both failed]"
    rc = 0 if (txt.strip() and not txt.startswith("[review unavailable")) else 1
    with open(out, "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt[-4000:])
    print("\n[hreview] %s review -> %s" % (lens, out))
    _log("CE review done: " + lens, "-> docs/ce/review_%s.txt" % lens, "ok")
    return rc


sys.exit(main())
